CC2021-WBL/GOOD-BOI-Application

src/App.js
src/components/pages/ClassSummaryPage.js
src/components/pages/CompetitorsPage.js
src/components/pages/ContestClassesPage.js
src/components/pages/ContestsPage.js
src/components/pages/ExcersisesPage.js
src/components/pages/HomePage.js
src/components/pages/LoginPage.js
src/components/pages/SingleSummaryPage.js

- Added 8 mock components 
- Added those components to App.js for testing purpose
closes #13

#13/UI/ 8 pages(views) - mock components

---

package-lock.json
package.json

-added prettier
-added fontawesome
TODO:
-eslint configuration
-package for ids

#7/PART/DEV/configruation-of-packages

---

dummy-data/competitions.js
dummy-data/competitors.js
dummy-data/doggos.js

-added 2 examlpes of dummy data in every of that files:
- competitions
- competitors
- dogs
Please read and let me know if it is all dummy data we need, or something else is necessary also

#27/DEV/dummy-data

---

node.js.yml

-added workflow
TODO
-check and add more actions, more tests

#8/DEV/PART/github-workflow

---

.eslintrc.json
package-lock.json
package.json

-added configuration in .eslintrc.json

#7/DEV/PART/configuration-of-packages

---

.gitignore

 #047/DEV/adding-idea-folder-to-gitignore 

---

src/varsStyledComponents.js

#36/UI/StyledComponentsVars

---

src/Pages/HomePage/HomePage.js

-- added -- and | to better see links

#56/FIX/Fixed Links text nicer to an eye

---

src/Atoms/InfoLabel/InfoLabelStyled.js
src/Molecules/ClassCompetitorButton/ClassOrDogButtonStyled.js

added COLORS from varsStyledComponents.js

#016/UI/class competitor button/fix COLORS

---

src/Atoms/FormWrapper/FormWrapper.js

#116/FIX/FormWrappers

---

src/Atoms/FooterProfileButton/FooterProfileButton.js
src/Atoms/FooterProfileButton/FooterProfileButtonStyled.js
src/Molecules/Footer/FooterStyled.js

Fixed styling: margin:0, padding: 1rem, background: white, removed PriSecBtn, removed hover color.
Closes #130

#130 fix: fixed styling

---

.stylelintrc
package-lock.json
package.json

closes #134 
Now, before push you should use this command: npm run lint:css

Added stylelint packages

---

src/Atoms/CheckboxAgreeField/CheckboxAgreeFieldStyled.js
src/Atoms/EditAccept/EditAcceptStyled.js
src/Atoms/Exercise/ExerciseStyled.js
src/Atoms/FooterProfileButton/FooterProfileButtonStyled.js
src/Atoms/FormWrapper/FormWrapperStyled.js
src/Atoms/GreyLabel/GreyLabelStyled.js
src/Atoms/InfoLabel/InfoLabelStyled.js
src/Atoms/InputLabel/InputLabelStyled.js
src/Atoms/NavElementStyled/LinkWrapperStyled.js
src/Atoms/NavElementStyled/LogoStyled.js
src/Atoms/PointsText/PointsTextStyled.js
src/Atoms/SpecialButton/SpecialButtonStyled.js
src/Molecules/ClassOrDogButton/ClassOrDogButtonStyled.js
src/Molecules/ContestComponent/ContestComponentStyled.js
src/Molecules/Footer/FooterStyled.js
src/Molecules/InputField/InputFieldStyled.js
src/Molecules/Points/PointsStyled.js
src/Molecules/PointsForm/PoinstFormStyled.js
src/Molecules/PointsForm/PointsInputStyled.js
src/Molecules/SpecialButtonsContainer/SpecialButtonsContainerStyled.js
src/Organisms/ExerciseCardsContainter/ExerciseCardsContainerStyled.js
src/Organisms/NavElement/NavElementStyled.js
src/Pages/LandingPage/LandingPageStyled.js
src/Styles/globalStyles.js

#137/ImprovedCss

---

src/App.js
src/Atoms/FormWrapper/FormWrapperStyled.js
src/Pages/HomePage/HomePage.js
src/Pages/HomePage/LinkStyled.js

Fixed branch name after errors with pipelines |
Fixed Routes paths after merge to be able to navigate through old navigation mock;
By the way, small fix to forgot pass wrapper (centering text)
closes #132

#132/FIX/routes paths

---

src/Atoms/SpecialButton/SpecialButton.js
src/Molecules/SpecialButtonsContainer/SpecialButtonsContainer.js
src/Organisms/Modal/Modal.js

- Fixed: PropTypes required erased

#67/FIX/RequiredProps

---

src/Atoms/ButtonsExercises/ButtonExercisesStyled.js
src/Atoms/ButtonsExercises/ButtonsExercises.js
src/Molecules/ButtonsExcercisenContainer/ButtonExercisesContainerStyled.js
src/Molecules/ButtonsExcercisenContainer/ButtonsExercisesContainer.js
src/Pages/ExercisesPage/ExercisesPage.js

First attempt to create Buttons

#93/UI/Buttons on exercises screen

---

src/Molecules/ClassOrDogButton/ClassOrDogButton.js
src/PagesBody/ClassesPage/ClassesPage.js

- Fixed: Classes Page and ClassOrDog button refactored to new data mock

#203/PARTII/Refactor-Cleanup

---

src/PagesBody/LandingPage/LandingPage.js

-Fixed: for logged user, landing page with only one button

#243 / Refactor / Landing Page

---

src/Molecules/Footer/Footer.js

- Refactored: profile button not availible for not logged in

#253/UI/PARTII/Refator profile button for not logged in

---

src/Atoms/MainButton/MainButton.js
src/Atoms/MainButton/MainButtonStyled.js

PR fix. Removed unneccessary files from scope.
Branch adds ability of the main button to change text justify.
Used only on classChoicePage.

#218/feat/added main button prop and fix style - PR fix

---

client/src/Consts/modalData.js
client/src/Organisms/ContestDetails/ContestDetailsToggler/ContestDetailsToggler.js
client/src/PagesBody/ClassesPage/ClassesPage.js
client/src/PagesBody/ContestsPage/ContestsPage.js
client/src/PagesBody/ProfilePage/ProfilePage.js
client/src/PagesBody/RolePage/RolePage.js
client/src/Tools/checkPathOrigin.js

closes #276 
Changed names from "konkursy" to "zawody" in ou app

#276/logic/changed everywhere from "konkurs" to "zawody"

---

server/Routes/contests.js

#324/Back/Endpoints/DeleteContest

---

client/src/Data/MongoDBMock/contestsV2.js
server/Controllers/contestControllers.js
server/Model/Contest.js
server/Tools/ModelTools.js

closes #349 
updated obedienceClasses property in mock, Schema and register contest endpoint --> from object with objects to array with objects, which has prop classNumber

#349/back/bugfix/update of contest schema, endpoint and mock

---

client/src/Data/MongoDBMock/contestsV2.js
client/src/Data/MongoDBMock/participants.js
client/src/PagesBody/RolePage/RolePage.js

closes #360
-updated roles page navigation to manager flow (/manager)
-added "manager" role to Matylda Borutka mock to have connection to that flow

#360/logic/FIX/actualization of manager button at role page 

---

client/src/Templates/Layout/Grid.js

Fixed: Grid columns set width for first column

#341/UI/PART IV/UserProfile

---

client/src/Atoms/DataLine/DataLineStyled.js
client/src/Organisms/Confirmation/ConfirmationStyled.js
client/src/PagesBody/ForbiddenEntryPage/ForbiddenEntryStyled.js
client/src/Styles/Themes.js

#406/UI/DarkMode/Desktop

---

client/src/Context/DogContext.js
client/src/Hooks/QueryHooks/useUserDogs.js
client/src/Organisms/DogData/DogData.js
client/src/Organisms/EnterCompetitionContainer/EnterCompetitionContainer.js
client/src/Organisms/NavElement/NavElement.js
client/src/Organisms/ParticipantData/ParticipantData.js
client/src/PagesBody/ClassChoicePage/ClassChoicePage.js
client/src/PagesBody/DogDataPage/DogDataPage.js
client/src/PagesBody/DogFormPage/DogFormPage.js
client/src/PagesBody/ParticipantDataPage/ParticipantDataPage.js
client/src/PagesBody/ProfilePage/ProfilePage.js
client/src/PagesBody/RolePage/RolePage.js
client/src/PagesBody/UserDogsPage/UserDogPage.js
client/src/Tools/FetchData/fetchFormsFunctions.js
server/Controllers/dogsControllers.js
server/Model/Dog.js
server/Routes/dogs.js

-updated DogContext to use useState instead useReducer. added fetching data in DogsConmtext for signed in user
-bugfixes in post new dog

Update POST new dog & DgosContext
